spring.config.import=optional:file:.env[.properties]
spring.application.name=notion-fuse

# PostgreSQL Database Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/notionfuse_db
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres123


# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=false

#jwt
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000

# OAuth2 Settings
notion.client.id=${NOTION_CLIENT_ID}
notion.client.secret=${NOTION_CLIENT_SECRET}
notion.redirect.uri=${NOTION_REDIRECT_URI}
notion.auth.url=https://api.notion.com/v1/oauth/authorize?owner=user&client_id=${NOTION_CLIENT_ID}&response_type=code&redirect_uri=${NOTION_REDIRECT_URI}

# Frontend Application URL Configuration
app.frontend.url=http://localhost:3000

# Email Settings
app.mail.enabled=true
app.mail.from=mhamadghourani155@gmail.com
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=aeac17001@smtp-brevo.com
spring.mail.password=${BREVO_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

