spring.application.name=notion-fuse

# PostgreSQL Database Settings
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driverClassName=org.postgresql.Driver
# Explicitly define the dialect to avoid 'Unable to determine Dialect' errors
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate Settings
# NOTE: 'create-drop' will delete your data every time the app restarts.
# Use 'update' for development.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=20

# JWT
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000

# OAuth2 Settings
notion.client.id=${NOTION_CLIENT_ID}
notion.client.secret=${NOTION_CLIENT_SECRET}
notion.redirect.uri=${NOTION_REDIRECT_URI}
notion.auth.url=https://api.notion.com/v1/oauth/authorize?owner=user&client_id=${NOTION_CLIENT_ID}&response_type=code&redirect_uri=${NOTION_REDIRECT_URI}

# Frontend
app.frontend.url=http://localhost:3000

# Email
app.mail.enabled=true
app.mail.from=mhamadghourani155@gmail.com
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=aeac17001@smtp-brevo.com
spring.mail.password=${BREVO_API_KEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true